global_frame: odom
rolling_window: true
width: 10
height: 10

plugins:
  - {name: obstacle_layer,                 type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,                 type: "costmap_2d::InflationLayer"}