map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

frequency: 50
publish_tf: false
print_diagnostics: true
sensor_timeout: 0.1
two_d_mode: true

pose0: /slam/pose
pose0_config: [true,  true,  true,
              true, true, true,
              true,  false, false,
              false, false, true,
              false, false, false]
pose0_differential: false
pose0_relative: false

# odom0: /propbot_velocity_controller/odom
# odom0_config: [false, false, false,
#                 false, false, false,
#                 true,  true,  true,
#                 false, false, false,
#                 false, false, false]
# odom0_queue_size: 10
# odom0_nodelay: true
# odom0_differential: false
# odom0_relative: false

imu0: /imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
imu0_relative: false

use_control: false